CREATE TABLE projects (id TEXT PRIMARY KEY, canon_version TEXT NOT NULL, calendar_version TEXT NOT NULL, style_version INTEGER NOT NULL);
INSERT INTO projects VALUES ('dayao','dayao-canon-1','dayao-simple-v1',1);
CREATE TABLE saves (id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE branches (id TEXT PRIMARY KEY, save_id TEXT NOT NULL REFERENCES saves(id), head_id TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE turns (id TEXT PRIMARY KEY, save_id TEXT NOT NULL REFERENCES saves(id), parent_id TEXT REFERENCES turns(id), branch_id TEXT NOT NULL, request_id TEXT UNIQUE NOT NULL, payload TEXT NOT NULL);
CREATE INDEX turns_save ON turns(save_id);
CREATE INDEX turns_parent ON turns(parent_id);
CREATE TABLE drafts (id TEXT PRIMARY KEY, save_id TEXT NOT NULL REFERENCES saves(id), branch_id TEXT NOT NULL, status TEXT NOT NULL, payload TEXT NOT NULL);
CREATE INDEX drafts_branch ON drafts(branch_id,status);
CREATE TABLE fact_events (id TEXT PRIMARY KEY, turn_id TEXT NOT NULL REFERENCES turns(id), payload TEXT NOT NULL);
CREATE TABLE npc_knowledge_events (id TEXT PRIMARY KEY, turn_id TEXT NOT NULL REFERENCES turns(id), payload TEXT NOT NULL);
CREATE TABLE memories (id TEXT PRIMARY KEY, turn_id TEXT NOT NULL REFERENCES turns(id), payload TEXT NOT NULL);
CREATE TABLE summaries (id TEXT PRIMARY KEY, turn_id TEXT NOT NULL REFERENCES turns(id), payload TEXT NOT NULL);
CREATE TABLE bookmarks (id TEXT PRIMARY KEY, save_id TEXT NOT NULL REFERENCES saves(id), payload TEXT NOT NULL);
CREATE TABLE annotations (id TEXT PRIMARY KEY, save_id TEXT NOT NULL REFERENCES saves(id), payload TEXT NOT NULL);
CREATE TABLE ooc_messages (id TEXT PRIMARY KEY, save_id TEXT NOT NULL REFERENCES saves(id), payload TEXT NOT NULL);
CREATE TABLE profiles (id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE settings (id TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE style_references (id TEXT PRIMARY KEY, filename TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL);
PRAGMA user_version=1;
