import { z } from 'zod';
import { validateScenario } from './package';
import {scenarioForm} from './edit-form';
export const CreateScenarioSchema=z.object({title:z.string().trim().min(1).max(100),world:z.string().max(100000),playerName:z.string().trim().min(1).max(100),playerDescription:z.string().max(100000),npcs:z.string().max(100000),opening:z.string().max(100000),style:z.string().max(100000),rulesText:z.string().max(100000).default(''),openingLocation:z.string().max(100).default(''),initialPresentIndices:z.array(z.number().int().min(0).max(199)).max(64).default([]),relationshipEnabled:z.boolean().default(false),romanceEnabled:z.boolean().default(false),relationshipStats:z.string().max(10000).default(''),worldStats:z.string().max(10000).default(''),calendarType:z.enum(['none','relative','fictional','gregorian']).default('none'),era:z.string().max(100).default(''),playerMode:z.enum(['fixed','customizable','selectable']).default('fixed'),openingMode:z.enum(['fixed','generated_from_seed','interactive_setup']).default('fixed')}).strict();
export type CreateScenarioInput=z.infer<typeof CreateScenarioSchema>;
const stats=(text:string)=>text.split('\n').map(s=>s.trim()).filter(Boolean).map(row=>{const [key,displayName,min,max,initial]=row.split(/[|｜]/).map(s=>s.trim());if(!key||!displayName)throw new Error('数值每行格式为 key｜名称｜最小｜最大｜初值');return {key,displayName,min:Number(min),max:Number(max),initial:Number(initial),step:2,sceneLimit:5,dynamicDefault:null};});
export function createScenarioDraft(raw:unknown,packageId='scenario_'+crypto.randomUUID().replaceAll('-','').slice(0,16)){
  const x=CreateScenarioSchema.parse(raw),characters=x.npcs.split('\n').map(s=>s.trim()).filter(Boolean).map((row,i)=>{const [displayName,...parts]=row.split(/[|｜]/);return {stableId:'character_'+String(i+1).padStart(3,'0'),displayName:displayName.trim(),identity:parts[0]?.trim()||'',description:parts.slice(1).join('｜')||parts[0]||'',romancePolicy:'disabled',initialStats:{}};});
  const player={id:'player',name:x.playerName,description:x.playerDescription};
  if(x.initialPresentIndices.some(i=>!characters[i]))throw new Error('开场人物序号超出初始 NPC 列表');
  return validateScenario({manifest:{schemaVersion:1,engineSchemaVersion:1,packageId,version:'1.0.0',title:x.title,description:'',author:'',language:'zh-CN',playerMode:x.playerMode,openingMode:x.openingMode,dynamicCharacters:true,relationshipSystem:{enabled:x.relationshipEnabled},timeSystem:x.calendarType!=='none',romanceSystem:x.romanceEnabled,roleSystem:true,allowBranches:true},world:x.world,player,playerChoices:x.playerMode==='selectable'?[{...player,choiceId:'protagonist_1'}]:[],characters,rules:{notes:x.rulesText,relationshipStats:x.relationshipEnabled?stats(x.relationshipStats):[],worldStats:stats(x.worldStats),triggers:[],evidenceCategories:x.relationshipEnabled?[{key:'support',playerWords:['支持','保护','兑现','support','protect'],narrativeWords:['支持','保护','兑现','supported','protected']}]:[],storyThreadTypes:['quest','promise','investigation','relationship','personal','mystery','custom']},opening:x.opening,style:x.style,calendar:{id:'calendar_'+packageId,type:x.calendarType,era:x.era,months:Array(12).fill(30),start:{year:x.calendarType==='gregorian'?2026:1,month:1,day:1,minuteOfDay:540},allowAdvance:x.calendarType!=='none'},locations:[{id:'opening_location',name:x.openingLocation||'开场地点（待作者设定）'}],initialScene:{locationId:'opening_location',weather:'',present:[...new Set(x.initialPresentIndices)].map(i=>characters[i].stableId),pendingThreads:[],accessionOffsetDays:0},ui:{worldStatsTitle:'世界状态',playerAddress:'',branchName:'主线',pinnedCharacters:characters.map(c=>c.stableId)}});
}
export function editScenarioDraft(baseRaw:unknown,formRaw:unknown){
  const base=validateScenario(baseRaw),form=CreateScenarioSchema.parse(formRaw),sameNpcs=form.npcs===scenarioForm(base).npcs;
  const fresh=createScenarioDraft({...form,npcs:sameNpcs?base.characters.map(c=>c.displayName).join('\n'):form.npcs},base.manifest.packageId);
  const characters=fresh.characters.map((c,i)=>base.characters[i]?{...base.characters[i],...(sameNpcs?{}:{displayName:c.displayName,identity:c.identity,description:c.description}),...(!form.romanceEnabled?{romancePolicy:'disabled' as const}:{}),initialStats:Object.fromEntries(Object.entries(base.characters[i].initialStats).filter(([key])=>fresh.rules.relationshipStats.some(s=>s.key===key)))}:c);
  const definitions=(kind:'relationshipStats'|'worldStats')=>fresh.rules[kind].map(d=>{const old=base.rules[kind].find(s=>s.key===d.key);return old?{...old,displayName:d.displayName,min:d.min,max:d.max,initial:d.initial}:d;});
  const locations=base.locations.map(l=>l.id===base.initialScene.locationId?{...l,name:form.openingLocation||l.name}:l);
  return validateScenario({...base,manifest:{...base.manifest,title:form.title,playerMode:form.playerMode,openingMode:form.openingMode,timeSystem:fresh.manifest.timeSystem,relationshipSystem:fresh.manifest.relationshipSystem,romanceSystem:form.romanceEnabled},world:form.world,player:{...base.player,name:form.playerName,description:form.playerDescription},playerChoices:form.playerMode==='selectable'?(base.playerChoices.length?base.playerChoices:fresh.playerChoices):[],characters,opening:form.opening,style:form.style,calendar:base.calendar.type===form.calendarType?{...base.calendar,era:form.era}:fresh.calendar,locations,initialScene:{...base.initialScene,present:form.initialPresentIndices.map(i=>characters[i].stableId)},rules:{...base.rules,notes:form.rulesText,relationshipStats:definitions('relationshipStats'),worldStats:definitions('worldStats'),triggers:base.rules.triggers.filter(r=>(form.romanceEnabled||!r.romanceRequired)&&(form.relationshipEnabled||r.scope==='world')),evidenceCategories:form.relationshipEnabled?base.rules.evidenceCategories:[]},ui:{...base.ui,pinnedCharacters:base.ui.pinnedCharacters.filter(id=>characters.some(c=>c.stableId===id))}});
}
export const TextScenarioSchema=z.object({title:z.string().max(100),world:z.string().max(100000),playerName:z.string().max(100),playerDescription:z.string().max(100000),npcs:z.string().max(100000),opening:z.string().max(100000),style:z.string().max(100000),rulesText:z.string().max(100000).default(''),uncertainties:z.array(z.string().max(500)).max(30)}).strict();
export function textDraft(text:string){
  const sections:Record<string,string>={};let current='world';for(const line of text.split('\n')){const heading=/^\s*(?:#{1,4}\s*)?(世界(?:观|背景)?|玩家(?:角色|人设)?|主角|NPC(?:人设)?|人物|开(?:局|场)|文风|叙事风格|写作风格|(?:剧情|关系)?规则)\s*[：:]?\s*$/.exec(line);if(heading){const label=heading[1];current=/世界/.test(label)?'world':/玩家|主角/.test(label)?'player':/NPC|人物/.test(label)?'npcs':/开/.test(label)?'opening':/规则/.test(label)?'rulesText':'style';continue;}sections[current]=(sections[current]?sections[current]+'\n':'')+line;}
  const player=sections.player?.trim()||'';const [name,...description]=player.split(/[|｜\n]/);return {title:'导入剧本',world:sections.world?.trim()||'',playerName:name||'玩家角色',playerDescription:description.join('\n'),npcs:sections.npcs?.trim()||'',opening:sections.opening?.trim()||'',style:sections.style?.trim()||'',rulesText:sections.rulesText?.trim()||'',uncertainties:!player?['原文没有明确玩家角色，请补充。']:[]};
}
