import type Database from 'better-sqlite3';
import { z } from 'zod';
import { builtInScenario,publicScenario,scenarioHash,summarize,validateScenario } from './package';
import type { ScenarioPackage } from './schema';
export class ScenarioLibrary{
  constructor(private db:Database.Database){}
  install(raw:unknown,builtIn=false){const p=validateScenario(raw),hash=scenarioHash(p),m=p.manifest;const old=this.db.prepare('SELECT hash,built_in FROM scenario_packages WHERE package_id=? AND version=?').get(m.packageId,m.version) as {hash:string;built_in:number}|undefined;const reserved=this.db.prepare('SELECT package_id FROM scenario_packages WHERE package_id=? AND built_in=1').get(m.packageId);if(reserved&&!builtIn&&(!old||old.hash!==hash))throw new Error('内置剧本 ID 保留，请复制为新剧本后编辑');if(old&&old.hash!==hash)throw new Error('该 ID 和版本已安装不同内容，请提升版本或复制为新剧本');if(!old)this.db.prepare('INSERT INTO scenario_packages VALUES (?,?,?,?,?,?)').run(m.packageId,m.version,hash,JSON.stringify(p),builtIn?1:0,new Date().toISOString());return summarize(p,old?!!old.built_in:builtIn);}
  ensureBuiltIn(){this.install(builtInScenario(),true);}
  list(){return (this.db.prepare('SELECT payload,built_in FROM scenario_packages ORDER BY installed_at,package_id,version').all() as {payload:string;built_in:number}[]).map(r=>summarize(JSON.parse(r.payload),!!r.built_in));}
  get(id:string,version?:string){const row=(version?this.db.prepare('SELECT payload FROM scenario_packages WHERE package_id=? AND version=?').get(id,version):this.db.prepare('SELECT payload FROM scenario_packages WHERE package_id=? ORDER BY installed_at DESC LIMIT 1').get(id)) as {payload:string}|undefined;if(!row)throw new Error('剧本未安装');return validateScenario(JSON.parse(row.payload));}
  snapshot(p:ScenarioPackage){const hash=scenarioHash(p);this.db.prepare('INSERT INTO scenario_snapshots VALUES (?,?,?,?) ON CONFLICT(hash) DO NOTHING').run(hash,p.manifest.packageId,p.manifest.version,JSON.stringify(p));return hash;}
  fromSnapshot(hash:string){const row=this.db.prepare('SELECT payload FROM scenario_snapshots WHERE hash=?').get(hash) as {payload:string}|undefined;if(!row)throw new Error('剧本快照缺失');return validateScenario(JSON.parse(row.payload));}
  preview(raw:unknown,original=''){const p=validateScenario(raw),id=crypto.randomUUID(),hash=scenarioHash(p);this.db.prepare('INSERT INTO scenario_previews VALUES (?,?,?,?)').run(id,hash,JSON.stringify(p),new Date().toISOString());return {previewId:id,hash,summary:summarize(p),package:p,original};}
  confirm(id:string,hash:string){const r=this.db.prepare('SELECT hash,payload FROM scenario_previews WHERE id=?').get(z.uuid().parse(id)) as {hash:string;payload:string}|undefined;if(!r||r.hash!==hash)throw new Error('预览已变更或不存在，请重新预览');return this.db.transaction(()=>{const result=this.install(JSON.parse(r.payload));this.db.prepare('DELETE FROM scenario_previews WHERE id=?').run(id);return result;})();}
  remove(id:string,version:string){return this.db.transaction(()=>{const p=this.get(id,version);const r=this.db.prepare('SELECT built_in FROM scenario_packages WHERE package_id=? AND version=?').get(id,version) as {built_in:number};if(r.built_in)throw new Error('内置示例不可删除；可以复制编辑');for(const row of this.db.prepare('SELECT payload FROM saves').all() as {payload:string}[]){const s=JSON.parse(row.payload);if(s.scenarioPackageId===id)throw new Error('已有存档引用此剧本，请先导出并归档存档；不会自动删除存档');}this.db.prepare('DELETE FROM scenario_packages WHERE package_id=? AND version=?').run(id,version);return summarize(p);})();}
  compare(saveHash:string,id:string,version:string){const before=this.fromSnapshot(saveHash),after=this.get(id,version);const sections=(Object.keys(after) as (keyof ScenarioPackage)[]).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]));const unsafe=sections.some(k=>!['manifest','style','lore','references','ui','assets'].includes(k))||JSON.stringify({...before.manifest,title:'',description:'',author:'',version:'',defaultNarrativeStyle:''})!==JSON.stringify({...after.manifest,title:'',description:'',author:'',version:'',defaultNarrativeStyle:''});return {sections,safe:!unsafe,before:summarize(before),after:summarize(after),note:unsafe?'人物、玩家、数值、历法或开场变更不能自动迁移，本存档继续使用旧快照。':'仅元数据、文风和 Lore 等变化可在明确确认后切换快照。'};}
  public(hash:string){return publicScenario(this.fromSnapshot(hash));}
}
