'use client';
import {useState} from 'react';
import Image from 'next/image';
import {blankScenarioForm,scenarioForm} from '../scenario/edit-form';
import {requestId} from '../client/storage';
import {apiResponse} from '../client/api';
import {browserEdition} from '../client/site-path';
import type {ScenarioPackage,ScenarioSummary} from '../scenario/schema';
import type {CreateScenarioInput} from '../scenario/draft';
import {Modal} from './Modal';
import {useAppDialog} from './useAppDialog';
type Api=<T>(path:string,data?:unknown)=>Promise<T>;
type Preview={previewId:string;hash:string;summary:ScenarioSummary;package:ScenarioPackage;original?:string};
const blank=blankScenarioForm;
export function ScenarioLibrary({scenarios,api,onChanged,onStart,offline}:{scenarios:ScenarioSummary[];api:Api;onChanged:()=>Promise<unknown>;onStart:(id:string,version:string)=>void;offline:boolean}){
  const {ask,dialog}=useAppDialog();const [form,setForm]=useState<CreateScenarioInput|null>(null),[original,setOriginal]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[advanced,setAdvanced]=useState(''),[editingBase,setEditingBase]=useState<ScenarioPackage|null>(null),[details,setDetails]=useState<ScenarioPackage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function run(fn:()=>Promise<void>){if(busy||offline)return;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const patch=(key:keyof CreateScenarioInput,value:string|boolean|number[])=>setForm(old=>old?{...old,[key]:value}:old);
  async function importZip(file:File){if(file.size>4*1024*1024)throw new Error('剧本 ZIP 限 4MB');const bytes=new Uint8Array(await file.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));setPreview(await api<Preview>('scenarios/import',{base64:btoa(bin)}));}
  async function assist(useAI:boolean){const result=await api<{draft:Omit<CreateScenarioInput,'relationshipEnabled'|'romanceEnabled'|'relationshipStats'|'worldStats'|'calendarType'|'era'|'playerMode'|'openingMode'>&{uncertainties:string[]};requestCount:number}>('scenarios/assist',{text:original,useAI,authorizeNetwork:useAI});const {uncertainties,...fields}=result.draft;setEditingBase(null);setAdvanced('');setForm({...blank,...fields});setNotice(uncertainties.join('；')||'转换结果是草稿，请核对原文。');}
  return <main className="page scenario-library"><div className="page-heading"><div><div className="eyebrow">不同世界，同一支笔</div><h1>剧本库</h1><p>剧本保存世界与规则；卷册保存这一局实际发生的故事。</p></div></div>
    {error&&<p role="alert" className="error-text">{error}</p>}{notice&&<p role="status">{notice}</p>}{offline&&<p>当前离线，可阅读已下载存档；安装或编辑剧本需要连接主服务。</p>}
    <div className="button-row"><button className="primary" disabled={offline||busy} onClick={()=>{setForm({...blank});setOriginal('');setAdvanced('');setEditingBase(null);}}>创建新剧本</button><label className="file-button">导入剧本 ZIP<input aria-label="导入剧本 ZIP" type="file" accept=".zip" disabled={offline||busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>importZip(file));e.target.value='';}}/></label><label className="file-button">导入背景 TXT／MD<input aria-label="导入背景 TXT／MD" type="file" accept=".txt,.md" disabled={offline||busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{if(file.size>512*1024)throw new Error('背景文本限 512KB');setOriginal(await file.text());setForm({...blank});setAdvanced('');setEditingBase(null);});e.target.value='';}}/></label></div>
    <div className="scenario-cards">{scenarios.map(s=><article className="scenario-card" key={s.packageId+':'+s.version}>{s.coverImage?<Image src={s.coverImage} alt={s.title+'封面'} width={600} height={320} unoptimized className="scenario-cover"/>:<div className="scenario-cover-empty" aria-hidden="true">{s.title.slice(0,1)}</div>}<h2>{s.title}</h2><p>{s.description}</p><small>{s.author||'作者未提供'} · {s.version}{s.builtIn?' · 内置示例':''}</small><p>玩家：{s.playerName} · 初始人物 {s.npcCount} · {s.romance?'允许恋爱机制':'无恋爱机制'}</p>{s.warnings.map(w=><p key={w}>{w}</p>)}<div className="button-row"><button className="primary" disabled={offline||busy||!!s.warnings.length} onClick={()=>onStart(s.packageId,s.version)}>开始新游戏</button><button disabled={offline||busy} onClick={()=>void run(async()=>setDetails(await api<ScenarioPackage>('scenarios/'+s.packageId+'?version='+s.version)))}>查看设定</button><a className="outline" download onClick={browserEdition()?e=>{e.preventDefault();void run(async()=>{const response=await apiResponse("scenarios/"+s.packageId+"/export?version="+s.version);if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob()),link=document.createElement("a");link.href=url;link.download=s.packageId+"-"+s.version+"-scenario.zip";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}:undefined} href={'/api/scenarios/'+s.packageId+'/export?version='+s.version}>导出剧本 ZIP</a><button disabled={offline||busy} onClick={()=>void run(async()=>{const p=await api<ScenarioPackage>('scenarios/'+s.packageId+'?version='+s.version);p.manifest.packageId='scenario_'+requestId().replaceAll('-','').slice(0,16);p.manifest.title+=' · 副本';p.manifest.version='1.0.0';setAdvanced(JSON.stringify(p,null,2));setEditingBase(p);setOriginal('');setForm(scenarioForm(p));})}>复制剧本</button><button disabled={offline||busy} onClick={()=>void run(async()=>{if(s.builtIn)throw new Error('内置示例请先复制，原剧本保持不变');const p=await api<ScenarioPackage>('scenarios/'+s.packageId+'?version='+s.version);const v=p.manifest.version.split('.').map(Number);p.manifest.version=v[0]+'.'+v[1]+'.'+(v[2]+1);setAdvanced(JSON.stringify(p,null,2));setEditingBase(p);setOriginal('');setForm(scenarioForm(p));})}>编辑／升级版本</button><button className="danger" disabled={s.builtIn||offline||busy} onClick={()=>void run(async()=>{const answer=await ask({title:'删除剧本',description:'在用剧本不会删除存档，也不能被删除。请输入剧本名称确认。',label:'剧本名称',expectedValue:s.title,required:true});if(answer===null)return;await api('scenarios/delete',{packageId:s.packageId,version:s.version,confirmation:answer});await onChanged();})}>删除</button></div></article>)}</div>
    {form&&<Modal title="创建／整理剧本" close={()=>{if(!busy)setForm(null);}}>{error&&<p role="alert" className="error-text">{error}</p>}{notice&&<p>{notice}</p>}<p>下列内容都可直接输入长文本。未知事实保持空白；保存前会展示预览。</p>
      <label>原始背景文本<textarea aria-label="原始背景文本" rows={6} maxLength={100000} value={original} onChange={e=>setOriginal(e.target.value)}/></label><div className="button-row"><button disabled={busy||!original.trim()} onClick={()=>void run(()=>assist(false))}>按标题直接整理</button><button disabled={busy||!original.trim()} onClick={()=>void run(()=>assist(true))}>AI 帮我整理设定</button></div><p className="muted">AI 按当前设置的供应商运行，可能计费；Mock 不发网络请求。转换不会自动安装。</p>
      {([['title','剧本名称'],['world','世界背景'],['playerName','玩家角色姓名'],['playerDescription','玩家人设'],['npcs','初始 NPC'],['opening','开局原文'],['style','写作风格'],['rulesText','剧情与关系规则']] as const).map(([key,label])=><label key={key}>{label}{key==='title'||key==='playerName'?<input aria-label={label} value={form[key]} onChange={e=>patch(key,e.target.value)}/>:<textarea aria-label={label} rows={4} maxLength={100000} placeholder={key==='npcs'?'每行：姓名｜身份｜描述；同名的人分行登记，使用不同 ID':undefined} value={form[key]} onChange={e=>patch(key,e.target.value)}/>}</label>)}
      <p className="muted">自然语言规则用于叙事参考；自动数值触发须在高级配置中声明。复制／编辑保留完整模板。同名人物按行登记；编辑时逐行修改，不按名字合并。</p><label>开场地点<input aria-label="开场地点" value={form.openingLocation} onChange={e=>patch('openingLocation',e.target.value)}/></label><fieldset><legend>开场已在场的 NPC（作者设定）</legend>{form.npcs.split('\n').map(s=>s.trim()).filter(Boolean).map((line,i)=><label key={i}><input type="checkbox" checked={form.initialPresentIndices.includes(i)} onChange={e=>patch('initialPresentIndices',e.target.checked?[...form.initialPresentIndices,i]:form.initialPresentIndices.filter(n=>n!==i))}/>{line.split(/[|｜]/)[0]}</label>)}</fieldset>
      <label>玩家模式<select value={form.playerMode} onChange={e=>patch('playerMode',e.target.value)}><option value="fixed">固定主角</option><option value="customizable">自定义姓名／人设</option><option value="selectable">选择主角（高级配置可添加更多候选）</option></select></label><label>开局类型<select value={form.openingMode} onChange={e=>patch('openingMode',e.target.value)}><option value="fixed">作者固定开场</option><option value="generated_from_seed">按开局条件生成第一幕</option><option value="interactive_setup">先填写主角，再显示开场</option></select></label>
      <label><input type="checkbox" checked={form.relationshipEnabled} onChange={e=>patch('relationshipEnabled',e.target.checked)}/>启用人物数值</label>{form.relationshipEnabled&&<label>自定义人物数值<textarea aria-label="自定义人物数值" placeholder="respect｜尊重｜0｜100｜20" value={form.relationshipStats} onChange={e=>patch('relationshipStats',e.target.value)}/></label>}<label><input type="checkbox" checked={form.romanceEnabled} onChange={e=>patch('romanceEnabled',e.target.checked)}/>允许恋爱机制（人物默认仍关闭，需明确配置）</label>
      <label>自定义世界状态<textarea aria-label="自定义世界状态" placeholder="clues｜线索｜0｜100｜0" value={form.worldStats} onChange={e=>patch('worldStats',e.target.value)}/></label><label>时间系统<select aria-label="时间系统" value={form.calendarType} onChange={e=>patch('calendarType',e.target.value)}><option value="none">无明确时间</option><option value="relative">第一天／第二天</option><option value="gregorian">现代公历</option><option value="fictional">可配置架空日历</option></select></label>{form.calendarType==='fictional'&&<label>年号<input value={form.era} onChange={e=>patch('era',e.target.value)}/></label>}
      <details><summary>高级结构化配置</summary><p>复制、编辑和升级版本使用完整配置，可设置候选主角、日历、地点、势力、角色、Lore 和声明式规则。点击下方高级预览采用这里的内容。</p><textarea aria-label="高级剧本配置" rows={12} value={advanced} onChange={e=>setAdvanced(e.target.value)}/><button disabled={!advanced.trim()||busy} onClick={()=>void run(async()=>setPreview(await api<Preview>('scenarios/preview',JSON.parse(advanced))))}>预览高级配置</button></details>
      <button className="primary" disabled={busy} onClick={()=>void run(async()=>setPreview({...await api<Preview>('scenarios/manual',editingBase?{form,base:editingBase}:form),original}))}>预览剧本</button>
    </Modal>}
    {preview&&<Modal title="安装前预览" close={()=>{if(!busy)setPreview(null);}}>{error&&<p role="alert" className="error-text">{error}</p>}<h2>{preview.summary.title}</h2><p>{preview.summary.author||'作者未提供'} · {preview.summary.version}</p><p>玩家：{preview.summary.playerName} · NPC {preview.summary.npcCount} · Lore {preview.summary.loreCount}</p><p>人物数值：{preview.summary.relationshipStats.join('、')||'关闭'} · 世界状态：{preview.summary.worldStats.join('、')||'无'}</p><p>动态人物：{preview.summary.dynamicCharacters?'开启':'关闭'} · 恋爱：{preview.summary.romance?'允许':'关闭'} · 隐藏信息：{preview.summary.hiddenInformation?'含有':'无'} · 开局：{preview.summary.openingMode}</p>{preview.summary.warnings.map(w=><p key={w}>{w}</p>)}{preview.original&&<details open><summary>原始设定</summary><p className="preserve-text">{preview.original}</p></details>}<details><summary>核对完整转换结果</summary><pre>{JSON.stringify(preview.package,null,2)}</pre></details><button className="primary" disabled={busy} onClick={()=>void run(async()=>{await api('scenarios/install',{previewId:preview.previewId,hash:preview.hash,confirmed:true});await onChanged();setPreview(null);setForm(null);setAdvanced('');setEditingBase(null);setNotice('剧本已安装，已有存档继续使用原快照。');})}>确认安装</button></Modal>}
    {details&&<Modal title={details.manifest.title+' · 作者设定'} close={()=>setDetails(null)}><p>这里是作者设定，可能包含未揭示背景；它不是本局历史。</p><h3>世界</h3><p className="preserve-text">{details.world}</p><h3>玩家</h3><p className="preserve-text">{details.player.name}：{details.player.description}</p><h3>人物</h3>{details.characters.map(c=><details key={c.stableId}><summary>{c.displayName} · {c.identity}</summary><p className="preserve-text">{c.background||c.description}</p><p className="preserve-text">{c.privateBackground}</p></details>)}<h3>固定开场／开局条件</h3><p className="preserve-text">{details.opening}</p><h3>写作风格</h3><p className="preserve-text">{details.style}</p></Modal>}{dialog}
  </main>;
}
