import {describe,it,expect} from 'vitest';
import {zipSync,unzipSync,strToU8} from 'fflate';
import {detectiveScenario} from '../fixtures/scenarios';
import {importPackageZip,packageZip,validateScenario,safePackagePath} from '../../src/scenario/package';
describe('不可信剧本包边界',()=>{
 const source=()=>unzipSync(packageZip(detectiveScenario()));
 it.each(['../world.md','/tmp/world.md','C:/file.md','characters/../../bad.md','folder\\bad.md','https://evil/world.md','a//b.md'])('rejects path %s without touching a filesystem',(name)=>{expect(()=>safePackagePath(name)).toThrow();expect(()=>importPackageZip(zipSync({...source(),[name]:strToU8('恶意数据')}))).toThrow();});
 it.each(['payload.js','payload.ts','payload.sh','payload.sql','assets/cover.svg','page.html','server.exe'])('rejects executable/HTML extension %s',(name)=>expect(()=>importPackageZip(zipSync({...source(),[name]:strToU8('content')}))).toThrow());
 it('bounds inflation, detects incomplete ZIP and CRC corruption, and rejects forged image content',()=>{expect(()=>importPackageZip(zipSync({...source(),'lore/large.md':strToU8('x'.repeat(512*1024+1))}))).toThrow(/过大/);const good=packageZip(detectiveScenario());expect(()=>importPackageZip(good.subarray(0,good.length-4))).toThrow(/截断|完整/);const b=Buffer.from(good);const end=b.length-22,dir=b.readUInt32LE(end+16);b.writeUInt32LE((b.readUInt32LE(dir+16)+1)>>>0,dir+16);expect(()=>importPackageZip(b)).toThrow(/CRC/);expect(()=>importPackageZip(zipSync({...source(),'assets/fake.png':strToU8('<script>alert(1)</script>')}))).toThrow(/签名/);});
 it('rejects symlinks from central-directory Unix attributes',()=>{const b=Buffer.from(packageZip(detectiveScenario())),dir=b.readUInt32LE(b.length-6);b.writeUInt32LE(0xa1ff0000,dir+38);expect(()=>importPackageZip(b)).toThrow(/链接/);});
 it('rejects active content, arbitrary rules, unknown fields and unsafe CSS/theme injection',()=>{for(const value of ['<script>alert(1)</script>','<iframe src="x">','javascript:alert(1)']){const p=detectiveScenario();p.world=value;expect(()=>validateScenario(p)).toThrow(/Script/);}const p=detectiveScenario() as unknown as Record<string,unknown>;p.serverPath='C:/private';expect(()=>validateScenario(p)).toThrow();const q=detectiveScenario();Reflect.set(q.ui.theme,'css','body{display:none}');expect(()=>validateScenario(q)).toThrow();const r=detectiveScenario();Reflect.set(r.rules,'javascript','eval("x")');expect(()=>validateScenario(r)).toThrow();});
 it('same names and offices are allowed with distinct IDs; duplicate stable IDs rejected',()=>{const p=detectiveScenario();p.characters[1].displayName=p.characters[0].displayName;expect(()=>validateScenario(p)).not.toThrow();p.characters[1].stableId=p.characters[0].stableId;expect(()=>validateScenario(p)).toThrow(/重复/);});
});
